### ISSUE TITLE
All data is blue

### ISSUE THREAD

**Issue by Ricardo1980** [foundry/MagnetoMeter#1]
Hello!
I'm teting this app, but in my iPhone 5S with iOS7 and my iPad Air 2 with iOS8, in both I see the bars blue, all of them, so I have no idea which method belongs to each arrow.
Probably is related to iOS7 flat design.
I attach a screenshot:
![image](https://cloud.githubusercontent.com/assets/738681/7899643/213592a2-072c-11e5-9dca-e6da915ce007.png)

**Comment by foundry** [comment]
There is a  [UIProgressView bug in iOS7 and iOS8](http://stackoverflow.com/questions/22311516/uiprogressview-custom-track-and-progress-images-in-ios-7-1).  

The UIProgressView properties `progressImage` and `trackImage`   are   broken, so I have switched to using `progressColor` and  `tintColor` instead.    

![img_8586](https://cloud.githubusercontent.com/assets/341731/7902114/b64ebfe0-07a3-11e5-98b1-1165ada1aad9.PNG). I've also adjusted the colours slightly - they were a bit too washed out - and added an app icon.

Thanks for letting me know about the issue.
